name: 'Deploy to AWS S3'
description: 'Deploy a static website via AWS S3.'
inputs: 
  bucket: 
    description: 'Name of the s3 bucket'
    required: true
  bucket-region:
    description: 'The region of the S3 bucket'
    required: false
    default: 'ap-south-1'
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
outputs:
  website-url: 
    description: The url of the deployed site
runs: 
  using: 'node16'
  main: 'main.js'
